[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "https://https://p3k2025.vercel.app//:splat"
  status = 200
  force = true
 
