[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "next dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
